spring:
  application:
    name: RatingSystem
  datasource:
    url: jdbc:postgresql://localhost:5432/rating_system
    username: rating_system_user
    password: ***
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate.ddl-auto: validate
    show-sql: true

#    ddl-auto: none